services:
  - type: web
    name: cv-analyzer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/src/app/templates
      mkdir -p /opt/render/project/src/app/static
      cp -r app/templates/* /opt/render/project/src/app/templates/
      cp -r app/static/* /opt/render/project/src/app/static/
    startCommand: python -m gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    autoDeploy: true
