services:
  - type: web
    name: cv-analyzer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      ls -la
      pwd
      ls -la app/
      echo "Creating directories..."
      mkdir -p app/templates
      mkdir -p app/static
      ls -la app/
    startCommand: python -m gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    autoDeploy: true
