services:
  - type: web
    name: cv-analyzer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo "Current directory:" && pwd
      echo "\nDirectory structure before:" && ls -R
      echo "\nCopying template files..."
      mkdir -p app/templates app/static
      cp -r /opt/render/project/src/app/templates/* app/templates/
      cp -r /opt/render/project/src/app/static/* app/static/
      echo "\nDirectory structure after:" && ls -R
    startCommand: python -m gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    autoDeploy: true
