services:
  - type: web
    name: cv-analyzer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cp -r app/templates /opt/render/project/src/app/
      cp -r app/static /opt/render/project/src/app/
    startCommand: python -m gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    autoDeploy: true
