services:
  - type: web
    name: cv-analyzer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo "Current directory:" && pwd
      echo "\nProject structure before:" && ls -R
      echo "\nCreating app directories..."
      mkdir -p app/templates app/static/css app/static/js
      echo "\nCopying template files..."
      cp -f app/templates/index.html app/templates/
      cp -f app/static/css/* app/static/css/
      cp -f app/static/js/* app/static/js/
      echo "\nProject structure after:" && ls -R
    startCommand: python -m gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    autoDeploy: true
