services:
  - type: web
    name: cv-analyzer
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libmupdf-dev
      pip install -r requirements.txt
    startCommand: python -m gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    autoDeploy: true
