services:
  - type: web
    name: cv-analyzer
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo "Current directory:" && pwd
      echo "\nProject structure:" && ls -R /opt/render/project/src
      echo "\nMoving to project directory..."
      cd /opt/render/project/src
      echo "\nCreating symbolic links..."
      ln -sf app/templates templates
      ln -sf app/static static
      echo "\nFinal structure:" && ls -la
    startCommand: |
      cd /opt/render/project/src && python -m gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    autoDeploy: true
